/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElS: typeof import('element-plus/es')['ElS']
  const ElSe: typeof import('element-plus/es')['ElSe']
  const ElSelectGroup: typeof import('element-plus/es')['ElSelectGroup']
}
