/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/user/Avatar.vue')['default']
    AvatarPicker: typeof import('./src/components/user/AvatarPicker.vue')['default']
    copy: typeof import('./src/components/user/UserRegister copy.vue')['default']
    CustomForm: typeof import('./src/components/form/CustomForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElChekco: typeof import('element-plus/es')['ElChekco']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FadeTransition: typeof import('./src/components/transitions/FadeTransition.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Leading: typeof import('./src/components/Leading.vue')['default']
    Page: typeof import('./src/components/page/Page.vue')['default']
    RecursiveMenu: typeof import('./src/components/menus/RecursiveMenu.vue')['default']
    RoundContainer: typeof import('./src/components/RoundContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/searchBar/SearchBar.vue')['default']
    TestCustomForm: typeof import('./src/components/form/TestCustomForm.vue')['default']
    UserIcon: typeof import('./src/components/user/UserIcon.vue')['default']
    UserInfo: typeof import('./src/components/user/UserInfo.vue')['default']
    UserLogin: typeof import('./src/components/user/UserLogin.vue')['default']
    'UserLogin.ok': typeof import('./src/components/user/UserLogin.ok.vue')['default']
    UserLogout: typeof import('./src/components/user/userLogout.vue')['default']
    UserRegister: typeof import('./src/components/user/UserRegister.vue')['default']
    'UserRegister.ok': typeof import('./src/components/user/UserRegister.ok.vue')['default']
    VideoBackground: typeof import('./src/components/videoBackground/index.vue')['default']
    ZoomTransition: typeof import('./src/components/transitions/ZoomTransition.vue')['default']
  }
}
